version: "3.8"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - hive-network
    volumes:
      - ./src:/var/www/html # hot reloading for development

  db:
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: hive
    volumes:
      - ./hive.sql:/docker-entrypoint-initdb.d/hive.sql
    networks:
      - hive-network

networks:
  hive-network:
    driver: bridge